spring:
  datasource:
    url: jdbc:mysql://localhost:3306/technical_blog
    username: root
    password: rahatul49
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


